sudo: required

language: c

services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull store/oracle/database-instantclient:12.2.0.1

script:
  - true
